version: "3.5"
services:
  app:
    image: veprof
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: app
    restart: always
    command: >
      bash -c " find . -name \*.pyc -delete &&
                cd /veprof && python manage.py collectstatic --noinput &&
                
                python manage.py flush --no-input &&
                python manage.py migrate &&
                python manage.py create_superuser &&
                
                gunicorn config.wsgi:application -b :8000 -w 2 --reload -t 15 --env DJANGO_SETTINGS_MODULE='config.settings'"
    env_file:
      - ./app.env
    volumes:
      - ../config/:/veprof/config/
      - ../fb_auth/:/veprof/fb_auth/
    ports:
      - "8000:8000"
    networks:
      - default

networks:
  default:
    driver: "bridge"
